### ISSUE TITLE
env.Bool is struggling with truth

### ISSUE THREAD

**Issue by hacker** [micromdm/go4#10]
If env.Bool is provided `true` as default (like, for instance, a default for `MICROMDM_TLS`) then there's no way it can return `false`. In case of micromdm that prevents the thing from using the LB for TLS using environment only.

**Comment by groob** [comment]
You're right. Want to send a pull request to fix it?

**Comment by hacker** [comment]
Sure… Note, though, that I'm no go programmer and it took me like half an hour to figure out how to run/test it ;-) (the language itself is no problem, being unfamiliar with tools is).

**Comment by groob** [comment]
That looks good enough. My only comment is that a `switch` statement would have perhaps been more appropriate. Congrats on your first Go =)

**Comment by hacker** [comment]
Thanks ;-)

You're right, the thing with unfamiliar language is that even when you know what you have at your disposal (because who would think there's a language with no `switch`), you don't know the syntax without looking up docs.
