### ISSUE TITLE
httputil: debug middleware swallows status code

### ISSUE THREAD

**Issue by groob** [micromdm/go4#7]
Because WriteHeader is implicit, http.StatusOK is always used.

**Comment by ppdouble** [comment]
> 	// WriteHeader sends an HTTP response header with the provided
	// status code.
	//
	// If WriteHeader is not called explicitly, the first call to Write
	// will trigger an implicit WriteHeader(http.StatusOK).
	// Thus explicit calls to WriteHeader are mainly used to
	// send error codes.
	//
	// The provided code must be a valid HTTP 1xx-5xx status code.
	// Only one header may be written. Go does not currently
	// support sending user-defined 1xx informational headers,
	// with the exception of 100-continue response header that the
	// Server sends automatically when the Request.Body is read.
	WriteHeader(statusCode int)

https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/net/http/server.go;l=145
